CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE payment_method AS ENUM (
    'CREDITCARD',
    'DEBITCARD',
    'PIX',
    'CASH'
);

CREATE TABLE "user" (
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    email varchar(50) NOT NULL,
    enabled boolean NOT NULL,
    password varchar(100) NOT NULL,
    username varchar(30) NOT NULL,
    PRIMARY KEY (uuid),
    CONSTRAINT UK_user_email UNIQUE (email),
    CONSTRAINT UK_user_username UNIQUE (username)
);

CREATE TABLE role (
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    name varchar(30) NOT NULL,
    PRIMARY KEY (uuid),
    CONSTRAINT UK_role_name UNIQUE (name)
);

CREATE TABLE user_role (
    user_uuid uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT FK_user_role_user FOREIGN KEY (user_uuid) REFERENCES "user"(uuid),
    CONSTRAINT FK_user_role_role FOREIGN KEY (role_id) REFERENCES "role"(uuid)
);

CREATE TABLE person (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(30) NOT NULL,
    last_name varchar(60) NOT NULL,
    cpf varchar(11) NOT NULL,
    user_uuid uuid NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK_person_cpf UNIQUE (cpf),
    CONSTRAINT UK_person_user_uuid UNIQUE (user_uuid),
    CONSTRAINT FK_person_user FOREIGN KEY (user_uuid) REFERENCES "user"(uuid)
);

CREATE TABLE category (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(40) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK_category_name UNIQUE (name)
);

CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    barcode varchar(13) NOT NULL,
    expiration_date date NOT NULL,
    stock_quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    path_image varchar(300),
    category_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK_product_barcode UNIQUE (barcode),
    CONSTRAINT FK_product_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE customer (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    registration_date date NOT NULL,
    person_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK_customer_person UNIQUE (person_id),
    CONSTRAINT FK_customer_person FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE employee (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    hiring_date date NOT NULL,
    termination_date date,
    salary numeric(10,2) NOT NULL,
    person_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK_employee_person UNIQUE (person_id),
    CONSTRAINT FK_employee_person FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE sale (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    discount numeric(10,2) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    payment_method payment_method NOT NULL,
    customer_id bigint,
    employee_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_sale_customer FOREIGN KEY (customer_id) REFERENCES customer(id),
    CONSTRAINT FK_sale_employee FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE sale_product (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    quantity bigint NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    sale_id bigint NOT NULL,
    product_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_sale_product_sale FOREIGN KEY (sale_id) REFERENCES sale(id),
    CONSTRAINT FK_sale_product_product FOREIGN KEY (product_id) REFERENCES product(id)
);